config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :hotels
  resources :sights
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'map' => 'pages#map', as: 'map'
end

app/models/sight.rb
class Sight < ApplicationRecord
	has_attached_file :picture, styles: { original: "1200x900>", main: "480x640#", large: "640x480#", medium: "320x240#", thumb: "100x100#" }, default_url: "/images/missing.png"
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/controllers/sights_controller.rb
class SightsController < ApplicationController
  before_action :set_sight, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]

  # GET /sights
  # GET /sights.json
  def index
    set_meta_tags title: 'Достопримечательности и интересные места Красной Поляны',
              description: 'Информация о достопримечательностях Красной Поляны: карты, адреса, путеводители',
              keywords: 'Красная Поляна, достопримечательности, карта, как добраться'
    @sights = Sight.all
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :index }
    end
  end

  # GET /sights/1
  # GET /sights/1.json
  def show
    set_meta_tags title: @sight.seo_title.present? ? @sight.seo_title : @sight.name,
              description: @sight.seo_description.present? ? @sight.seo_description : @sight.excerpt,
              keywords: @sight.seo_keywords.present? ? @sight.seo_keywords : @sight.name + ', Красная Поляна, как добраться'
  end

  # GET /sights/new
  def new
    @sight = Sight.new
  end

  # GET /sights/1/edit
  def edit
  end

  # POST /sights
  # POST /sights.json
  def create
    @sight = Sight.new(sight_params)

    respond_to do |format|
      if @sight.save
        format.html { redirect_to @sight, notice: 'Sight was successfully created.' }
        format.json { render :show, status: :created, location: @sight }
      else
        format.html { render :new }
        format.json { render json: @sight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sights/1
  # PATCH/PUT /sights/1.json
  def update
    respond_to do |format|
      if @sight.update(sight_params)
        format.html { redirect_to @sight, notice: 'Sight was successfully updated.' }
        format.json { render :show, status: :ok, location: @sight }
      else
        format.html { render :edit }
        format.json { render json: @sight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sights/1
  # DELETE /sights/1.json
  def destroy
    @sight.destroy
    respond_to do |format|
      format.html { redirect_to sights_url, notice: 'Sight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sight
      @sight = Sight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sight_params
      params.require(:sight).permit(:picture, :name, :excerpt, :content, :coordinates, :top, :seo_title, :seo_description, :seo_keywords)
    end
end

app/helpers/sights_helper.rb
module SightsHelper
end

app/views/sights/_form.html.erb
<%= form_for sight, html: { multipart: true } do |f| %>
  <% if sight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sight.errors.count, "error") %> prohibited this sight from being saved:</h2>

      <ul>
      <% sight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <br/>
    <% if sight.picture? %>
      <%= image_tag sight.picture.url(:thumb) %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :excerpt %>
    <%= f.text_field :excerpt, class: 'form-control'  %>
  </div>

  <p>Для карт в нужном месте вставляем: <xmp><div id="location-canvas"></div></xmp>Для параграфа с маршрутом: <xmp><p class="directions">Текст маршрута</p></xmp></p>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :coordinates %>
    <%= f.text_field :coordinates, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= f.label :top %>
    <%= f.check_box :top %>
  </div>
  
  <div class="jumbotron">
    <h2>SEO</h2>
    <div class="form-group">
      <%= f.label :seo_title %>
      <%= f.text_field :seo_title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :seo_description %>
      <%= f.text_area :seo_description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :seo_keywords %>
      <%= f.text_area :seo_keywords, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Сохранить", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/sights/edit.html.erb
<div class="container edit-form">
	<h1>Editing Sight</h1>

	<%= render 'form', sight: @sight %>

	<%= link_to 'Show', @sight %> |
	<%= link_to 'Back', sights_path %>
</div>

app/views/sights/index.html.erb
<section class="sights">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <nav aria-label="breadcrumb">
      <ol class='breadcrumb'>
          <li class="breadcrumb-item">
            <%= link_to 'Главная', root_path %>
          </li>
          <li class="breadcrumb-item active">
            Что посмотреть?
          </li>
      </ol>
    </nav>
    <h1>Достопримечательности Красной Поляны</h1>
    <p>Достопримечательности и самые интересные места Красной Поляны. Описания, расположение на карте, маршруты, цены и отзывы.</p>
    <div class="row">
      <% @sights.each do |sight| %>
        <div class="col-sm-6">
          <div class="card">
            <%= image_tag sight.picture.url(:large), class: 'img-fluid card-img-top' %>
            <div class="card-body">
              <h5 class="card-title"><%= sight.name %></h5>
              <p class="card-text"><%= sight.excerpt %></p>
              <%= link_to 'Читать полностью &rarr;'.html_safe, sight, class: 'btn btn-primary' %>
              <% if user_signed_in? %>
                <p>
                  <ul class="list-inline">
                    <li class="list-inline-item"><%= link_to 'Edit', edit_sight_path(sight) %></li>
                    <li class="list-inline-item"><%= link_to 'Destroy', sight, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  </ul>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <% if user_signed_in? %><%= link_to 'New Sight', new_sight_path, class: 'btn btn-default' %><% end %>
  </div>
</section>

app/views/sights/index.xml.erb
<rss
    xmlns:yandex="http://news.yandex.ru"
    xmlns:media="http://search.yahoo.com/mrss/"
    xmlns:turbo="http://turbo.yandex.ru"
    version="2.0"
>
    <channel>
    	<% @sights.each do |sight| %>
        <item turbo="true">
           <link><%= request.base_url + '/sights/' + sight.id.to_s %></link>
           <turbo:content>
	           <![CDATA[
	                   <header>
	                       <h1><%= sight.name %></h1>
	                   </header>
	                   <figure>
	                      <%= image_tag sight.picture.url(:large) %>
	                      <figcaption><%= sight.name %></figcaption>
	                   </figure>
	                   <h2>Описание достопримечательности</h2>
	                   <p><%= sight.content.html_safe rescue 0 %></p>
	               ]]>
           </turbo:content>
        </item>
        <% end %>
    </channel>
</rss>

app/views/sights/new.html.erb
<div class="container edit-form">
	<h1>New Sight</h1>

	<%= render 'form', sight: @sight %>

	<%= link_to 'Back', sights_path %>
</div>

app/views/sights/show.html.erb
<section class="sight">
	<div class="container">
		<p id="notice"><%= notice %></p>
		<nav aria-label="breadcrumb">
		  <ol class='breadcrumb'>
		  	  <li class="breadcrumb-item">
		        <%= link_to 'Главная', root_path %>
		      </li>
		      <li class="breadcrumb-item">
		        <%= link_to 'Что посмотреть?', sights_path %>
		      </li>
		      <li class="breadcrumb-item active" aria-current="page">
		        <%= @sight.name %>
		      </li>
		  </ol>
		</nav>
		<h1><%= @sight.name %></h1>
		<%= @sight.content.html_safe rescue 0 %>
		<p><strong>Статья была полезной? Поделитесь с друзьями:</strong>
			<div class="addthis_inline_share_toolbox"></div>
		</p>
		<p>
          <div id="vk_comments"></div>
          <script type="text/javascript">
          VK.Widgets.Comments("vk_comments", {limit: 10, attach: "*"});
          </script>
        </p>
        <% if user_signed_in? %>
			<p>
				<%= link_to 'Edit', edit_sight_path(@sight) %> |
				<%= link_to 'Back', sights_path %>
			</p>
		<% end %>
</section>
<script>
var myLatlng = new google.maps.LatLng(<%= @sight.coordinates.split(',')[1] %>, <%= @sight.coordinates.split(',')[0]%>);
var mapOptions = {
  zoom: 10,
  center: myLatlng
}
var map = new google.maps.Map(document.getElementById("location-canvas"), mapOptions);

var marker = new google.maps.Marker({
    position: myLatlng,
    title:"Hello World!"
});

// To add the marker to the map, call setMap();
marker.setMap(map);
</script>