config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :hotels
  resources :sights
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'map' => 'pages#map', as: 'map'
end

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :excerpt %>
    <%= f.text_field :excerpt, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="jumbotron">
    <h2>SEO</h2>
    <div class="form-group">
      <%= f.label :seo_title %>
      <%= f.text_field :seo_title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :seo_description %>
      <%= f.text_area :seo_description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :seo_keywords %>
      <%= f.text_area :seo_keywords, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Сохранить", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="container edit-form">
	<h1>Editing Page</h1>

	<%= render 'form', page: @page %>

	<%= link_to 'Show', @page %> |
	<%= link_to 'Back', pages_path %>
</div>

app/views/pages/home.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/top_sights' %>
<%= render 'layouts/top_hotels' %>
<%= render 'layouts/info' %>

app/views/pages/index.html.erb
<section class="pages">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <ol class='breadcrumb'>
        <li class="breadcrumb-item">
          <%= link_to 'Главная', root_path %>
        </li>
        <li class="breadcrumb-item active">
          Статьи
        </li>
    </ol>
    <div class="title">
      <h1>Статьи о Красной Поляне</h1>
      <p>Полезная информация для гостей Красной Поляны</p>
    </div>
    <div class="row">
      <% @pages.each do |page| %>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= page.name %></h5>
              <p class="card-text"><%= page.excerpt %></p>
              <%= link_to 'Читать полностью &rarr;'.html_safe, page, class: 'btn btn-primary' %>
              <% if user_signed_in? %>
              <p>
                <ul class="list-inline">
                  <li class="list-inline-item"><%= link_to 'Edit', edit_page_path(page) %></li>
                  <li class="list-inline-item"><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <% if user_signed_in? %><%= link_to 'New Page', new_page_path, class: 'btn btn-default' %><% end %>
  </div>
</section>

app/views/pages/index.xml.erb
<rss
    xmlns:yandex="http://news.yandex.ru"
    xmlns:media="http://search.yahoo.com/mrss/"
    xmlns:turbo="http://turbo.yandex.ru"
    version="2.0"
>
    <channel>
    	<% @pages.each do |page| %>
        <item turbo="true">
           <link><%= request.base_url + '/pages/' + page.id.to_s %></link>
           <turbo:content>
	           <![CDATA[
	                   <header>
	                       <h1><%= page.name %></h1>
	                   </header>
	                   <p><%= page.content.html_safe rescue 0 %></p>
	               ]]>
           </turbo:content>
        </item>
        <% end %>
    </channel>
</rss>

app/views/pages/map.html.erb
<section class="map">
	<div class="container">
		<p id="notice"><%= notice %></p>
	    <ol class='breadcrumb'>
	        <li class="breadcrumb-item">
	          <%= link_to 'Главная', root_path %>
	        </li>
	        <li class="breadcrumb-item active">
	          Отели Красной Поляны на карте
	        </li>
	    </ol>
		<div class="heading">
			<h1>Отели Красной Поляны на карте</h1>
			<p>Для вашего удобства мы разработали карту на которой вы сможете посмотреть расположение интересующих вас отелей и достпримечательностей, а так же ознакомиться с расстоянием и местоположением объектов относительно подъемников и склонов.</p>
		</div>
		<div class="list-map">
			<div id="location-canvas" style="width:100%;height:500px;"></div>
		</div>
		<table class="table table-striped">
			<tbody>
			
				<% @hotels.each do |hotel| %>
				<tr>
					<td><%= hotel.name %></td> 
					<td><%= link_to 'на карте', "javascript:google.maps.event.trigger(gmarkers['#{hotel.name}'],'click');", class: 'hotel-link' %></td> 
					<td><%= link_to 'на странице', hotel %></td>
				</tr>
				<% end %>
			
		</tbody>
		</table>
	</div>
</section>
<script>
var locations = function() {
  var a = null;
  $.ajax({async:!1, global:!1, url:"/hotels.json", dataType:"json", success:function(b) {
    a = b;
  }});
  return a;
}();
gmarkers = [];
var map = new google.maps.Map(document.getElementById("location-canvas"), {zoom:14, center:new google.maps.LatLng(43.676, 40.28), mapTypeId:google.maps.MapTypeId.ROADMAP, scrollwheel:!1}), infowindow = new google.maps.InfoWindow;
function createMarker(a, b) {
  var c = new google.maps.Marker({position:a, map:map});
  google.maps.event.addListener(c, "click", function() {
    infowindow.setContent(b);
    infowindow.open(map, c);
  });
  return c;
}
for (var i = 0; i < locations.length; i++) {
  var data = locations[i];
  gmarkers[data.name] = createMarker(new google.maps.LatLng(data.coordinates.split(",")[0], data.coordinates.split(",")[1]), "<b>" + data.name + "</b><br/><a href='/hotels/" + data.id + "'>перейти</a>");
};
</script>

app/views/pages/new.html.erb
<div class="container edit-form">
	<h1>New Page</h1>

	<%= render 'form', page: @page %>

	<%= link_to 'Back', pages_path %>
</div>

app/views/pages/show.html.erb
<section class="page">
	<div class="container">
		<p id="notice"><%= notice %></p>
		<ol class='breadcrumb'>
          <li class="breadcrumb-item">
            <%= link_to 'Главная', root_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Статьи', pages_path %>
          </li>
          <li class="breadcrumb-item active">
            <%= @page.name %>
          </li>
       </ol>
		<h1><%= @page.name %></h1>
		<%= @page.content.html_safe rescue 0 %>
		<p><strong>Статья была полезной? Поделитесь с друзьями:</strong>
			<div class="addthis_inline_share_toolbox"></div>
		</p>
		<p>
          <div id="vk_comments"></div>
          <script type="text/javascript">
          VK.Widgets.Comments("vk_comments", {limit: 10, attach: "*"});
          </script>
        </p>
    <% if user_signed_in? %>
  		<p>
  			<%= link_to 'Edit', edit_page_path(@page) %> |
  			<%= link_to 'Back', pages_path %>
  		</p>
    <% end %>
</section>