config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :hotels
  resources :sights
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'map' => 'pages#map', as: 'map'
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  after_create :add_external
 
  has_attached_file :picture, styles: { original: "1200x900>", large: "640x480#", medium: "320x240#", thumb: "100x100#" }, default_url: "/images/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  self.per_page = 12

  def add_external
  	uri = URI(self.data_url)
	  response = Net::HTTP.get(uri)
	  data = JSON.parse(response, object_class: OpenStruct)
	  self.external = data
	  self.rating = self.external['table']['rating'].to_f rescue 0
	  self.stars = self.external['table']['stars'].to_i rescue 0
	  self.price = self.external['table']['price'].to_i rescue 0
	  self.rooms = get_rooms(self.external['table']['link'])
	  self.reviews = get_reviews(self.external['table']['link'])
	  self.services = get_services(self.external['table']['link'])
	  self.save
  end

  def get_rooms(link)
    doc = Nokogiri::HTML(open(link+"?prefer_site_type=tdot", "User-Agent" => "Chrome/15.0.854.0"), nil, "UTF-8")
    parsed_rooms = doc.css('table.roomstable').first
    parsed_rooms.search('thead', '.bed-types-wrapper','.bedroom_bed_type',  '.toggle-room-info', '.editDatesForm','.occ_no_dates','.rt_show_dates').remove
    rooms = parsed_rooms
    return rooms
  end

  def get_reviews(link)
    doc = Nokogiri::HTML(open(link+"?prefer_site_type=tdot", "User-Agent" => "Chrome/15.0.854.0"), nil, "UTF-8")
    parsed_reviews = doc.css('div.multi_reviews').first
    parsed_reviews.search('h3', '.request-more-reviews').remove
    reviews = parsed_reviews
    return reviews
  end

  def get_services(link)
    doc = Nokogiri::HTML(open(link+"?prefer_site_type=tdot", "User-Agent" => "Chrome/15.0.854.0"), nil, "UTF-8")
    return doc.css('div.facilities-checklist.dark-headings').first
  end

  def picture_remote_url=(url)
    self.picture = open(url)
  end

  def coordinates
    self.external['table']['coordinates']
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]

  # GET /hotels
  # GET /hotels.json
  def index
    set_meta_tags title: 'Отели и гостиницы Красной Поляны',
              description: 'Лучшие отели и гостиницы Красной Поляны. Цены, фотографии, номера и бронирование.',
              keywords: 'Красная Поляна, отели, гостиницы, бронирование'
    @q = Hotel.ransack(params[:q])
    @hotels = @q.result(distinct: true).page(params[:page]).order('name ASC')
    @all_hotels = Hotel.all
    data = Hotel.all.as_json(only: [:id, :name, :coordinates], root: false) 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: data }
      format.xml { render :index }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    set_meta_tags title: @hotel.name,
              description: @hotel.external['table']['description'],
              keywords: @hotel.name + ', отель, бронирование, фото, цены, номера, отзывы, Красная Поляна'
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:picture, :name, :data_url, :stars, :price, :rating, :rooms, :services, :reviews, :booking_script, :top)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for hotel, html: { multipart: true } do |f| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
    <br/>
    <% if hotel.picture? %>
      <%= image_tag hotel.picture.url(:thumb) %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :data_url %>
    <%= f.text_field :data_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :stars %>
    <%= f.number_field :stars, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :rooms %>
    <%= f.text_area :rooms, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :services %>
    <%= f.text_area :services, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :reviews %>
    <%= f.text_area :reviews, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :booking_script %>
    <%= f.text_area :booking_script, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :top %>
    <%= f.check_box :top %>
  </div>
  
  <div class="actions">
    <%= f.submit "Сохранить", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<div class="container edit-form">
	<h1>Editing Hotel</h1>

	<%= render 'form', hotel: @hotel %>

	<%= link_to 'Show', @hotel %> |
	<%= link_to 'Back', hotels_path %>
</div>

app/views/hotels/index.html.erb
<section class="hotels">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <nav aria-label="breadcrumb">
      <ol class='breadcrumb'>
          <li class="breadcrumb-item">
            <%= link_to 'Главная', root_path %>
          </li>
          <li class="breadcrumb-item active">
            Отели
          </li>
      </ol>
    </nav>
    <div class="title">
      <h1>Отели Красной Поляны</h1>
      <p>На основе личного опыта и отзывов гостей мы отобрали для вас только лучшие отели Красной Поляны: смело бронируйте любой из отелей ниже и мы гарантируем, что вы останетесь довольны отдыхом!</p>
      <div class="filter">
        <%= search_form_for @q, :html => {class: 'form-inline'} do |f| %>
          <div class="form-group mx-sm-3 mb-2">
            <%= f.search_field :name_cont, placeholder: "Введите название отеля", class: 'form-control' %>
          </div>
          <%= f.submit "Найти", class: 'btn btn-default mb-2' %>
        <% end %>
        <ul class="list-inline mx-sm-3 mb-2">
          <li class="list-inline-item"><strong>Упорядочить по:</strong></li>
          <li class="list-inline-item"><%= sort_link(@q, :stars, 'количеству звезд', default_order: :desc) %></li>
          <li class="list-inline-item"><%= sort_link(@q, :rating, 'рейтингу', default_order: :desc) %></li>
          <li class="list-inline-item"><%= sort_link(@q, :price, 'цене', default_order: :desc) %></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <% @hotels.each do |hotel| %>
        <div class="col-md-4 text-center">
            <%= link_to hotel do %>
              <%= image_tag (hotel.picture.url(:medium)), class: 'img-fluid' %>
            <% end %>
          <div class="item">
            <h3><%= link_to hotel.name, hotel %></h3>
            <ul class="list-inline star-rating">
              <% hotel.stars.times do %>
              <li class="list-inline-item star"><%= icon('fas', 'star') %></li>
              <% end %>
            </ul>

            <p class=""><%= hotel.external['table']['description'] %></p>
            <%= link_to 'Номера и цены ⟶', hotel, class: "btn btn-primary" %>
            <% if user_signed_in? %>
              <ul class="list-inline">
                <li class="list-inline-item"><%= link_to 'Edit', edit_hotel_path(hotel) %></li>
                <li class="list-inline-item"><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <p><%= will_paginate @hotels, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %><p>
    <% if user_signed_in? %><p><%= link_to 'New Hotel', new_hotel_path, class: 'btn btn-primary' %></p><% end %>
  </div>
</section>

app/views/hotels/index.xml.erb
<rss
    xmlns:yandex="http://news.yandex.ru"
    xmlns:media="http://search.yahoo.com/mrss/"
    xmlns:turbo="http://turbo.yandex.ru"
    version="2.0"
>
    <channel>
    	<% @all_hotels.each do |hotel| %>
        <item turbo="true">
           <link><%= request.base_url + '/hotels/' + hotel.id.to_s %></link>
           <turbo:content>
	           <![CDATA[
	                   <header>
	                       <h1><%= hotel.name %></h1>
	                   </header>
	                   <figure>
	                      <%= image_tag hotel.external['table']['image'] %>
	                      <figcaption><%= hotel.name %></figcaption>
	                   </figure>
	                   <h2>Описание отеля</h2>
	                   <p><%= hotel.external['table']['summary'] %></p>
	                   <ul>
	                   <h2>Услуги в отеле</h2>
	                   <% hotel.external['table']['services'].each do |service| %>
	                       <li><%= service %></li>
	                   <% end %>
	                   </ul>
	                   <p><%= link_to ("#{image_tag 'button.svg'}").html_safe, hotel.external['table']['link'] + "?aid=1632186&no_rooms=1&group_adults=2&room1=A%2CA", class: 'cta-button' %></p>
	               ]]>
           </turbo:content>
        </item>
        <% end %>
    </channel>
</rss>

app/views/hotels/new.html.erb
<div class="container edit-form">
	<h1>New Hotel</h1>

	<%= render 'form', hotel: @hotel %>

	<%= link_to 'Back', hotels_path %>
</div>

app/views/hotels/show.html.erb
<section class="hotel">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <nav aria-label="breadcrumb">
      <ol class='breadcrumb'>
          <li class="breadcrumb-item">
            <%= link_to 'Главная', root_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to 'Отели', hotels_path %>
          </li>
          <li class="breadcrumb-item active">
            <%= @hotel.name %>
          </li>
      </ol>
    </nav>
    <ul class="list-inline heading">
      <li class="list-inline-item">
        <h1><%= truncate(@hotel.name, length: 36, omission:"") %></h1>
        <ul class="list-inline star-rating">
          <% @hotel.stars.times do %>
          <li class="list-inline-item star"><%= icon('fas', 'star') %></li>
          <% end %>
        </ul>
        <p><%= icon('fas', 'map-marker-alt') %></i> <%= @hotel.external['table']['address'] %></p>
      </li>
      <li class="list-inline-item float-lg-right">
        <%= link_to ("#{image_tag 'button.svg'}").html_safe, @hotel.external['table']['link'] + "?aid=1632186&no_rooms=1&group_adults=2&room1=A%2CA", class: 'cta-button' %>
      </li>
    </ul>
    <%= react_component 'PageGallery', { photos: @hotel.external['table']['photos'] }, {prerender: true} %>
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="pills-description-tab" data-toggle="pill" href="#pills-description" role="tab" aria-controls="pills-description" aria-selected="true">Описание</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-rooms-tab" data-toggle="pill" href="#pills-rooms" role="tab" aria-controls="pills-rooms" aria-selected="false">Номера</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-services-tab" data-toggle="pill" href="#pills-services" role="tab" aria-controls="pills-services" aria-selected="false">Услуги</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-reviews-tab" data-toggle="pill" href="#pills-reviews" role="tab" aria-controls="pills-reviews" aria-selected="false">Отзывы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="pills-booking-tab" data-toggle="pill" href="#pills-booking" role="tab" aria-controls="pills-booking" aria-selected="false"><strong>Цены и бронирование</strong></a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-description" role="tabpanel" aria-labelledby="pills-description-tab">
        <h2>Описание отеля <%= @hotel.name %></h2>
        <p><%= @hotel.external['table']['description'] %></p>
        <p>
          К усугам наших гостей предлагаются:
          <ul>
            <% @hotel.external['table']['services'].each do |service| %>
              <li><%= service %></li>
            <% end %>
          </ul>
        </p>
        <p class="summary"><%= @hotel.external['table']['summary'] %></p>
      </div>
      <div class="tab-pane fade" id="pills-rooms" role="tabpanel" aria-labelledby="pills-rooms-tab">
        <h2>Номера и фото <%= @hotel.name %></h2>
        <p><%= @hotel.rooms.html_safe rescue 0 %></p>
      </div>
      <div class="tab-pane fade" id="pills-services" role="tabpanel" aria-labelledby="pills-services-tab">
        <h2>Услуги в <%= @hotel.name %></h2>
        <p><%= @hotel.services.html_safe rescue 0 %></p>
      </div>
      <div class="tab-pane fade" id="pills-reviews" role="tabpanel" aria-labelledby="pills-reviews-tab">
        <h2>Отзывы о <%= @hotel.name %></h2>
        <p>
          <div id="vk_comments"></div>
          <script type="text/javascript">
          VK.Widgets.Comments("vk_comments", {limit: 10, attach: "*"});
          </script>
        </p>
      </div>
      <div class="tab-pane fade" id="pills-booking" role="tabpanel" aria-labelledby="pills-booking-tab">
        <h2>Цены и бронирование <%= @hotel.name %></h2>
        <p><%= @hotel.booking_script.html_safe rescue 0 %></p>
      </div>
    </div>
    <p><strong>Расскажите об отеле друзьям:</strong>
      <div class="addthis_inline_share_toolbox"></div>
    </p>
  </div> 
</section>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_hotel_path(@hotel) %> |
  <%= link_to 'Back', hotels_path %>
<% end %>

<script type="text/javascript">
  function setImages() { 
    var divs = document.querySelectorAll('.room-info-slider');
    Array.prototype.forEach.call(divs, function(elements, index) {
      var spans = elements.getElementsByTagName("span");
      for(j=0;j<spans.length;j++) {
        spans[j].insertAdjacentHTML('beforeend', "<a class='chocolat-image' href=" + spans[j].dataset.imageHighRes + "><img class='img-fluid' src=" + spans[j].dataset.image +"></a>");
      }
    });
  }
  $(document).ready(function() {
    setImages();
    $('.room-info-slider').Chocolat();
  })
</script>

app/views/hotels/show.xml.erb
<rss
    xmlns:yandex="http://news.yandex.ru"
    xmlns:media="http://search.yahoo.com/mrss/"
    xmlns:turbo="http://turbo.yandex.ru"
    version="2.0"
>
    <channel>
        <item turbo="true">
           <link><%= request.original_url %></link>
           <turbo:content>
	           <![CDATA[
	                   <header>
	                       <h1><%= @hotel.name %></h1>
	                   </header>
	                   <figure>
	                      <%= image_tag @hotel.external['table']['image'] %>
	                      <figcaption><%= @hotel.name %></figcaption>
	                   </figure>
	                   <h2>Описание отеля</h2>
	                   <p><%= @hotel.external['table']['summary'] %></p>
	                   <ul>
	                   <h2>Услуги в отеле</h2>
	                   <% @hotel.external['table']['services'].each do |service| %>
	                       <li><%= service %></li>
	                   <% end %>
	                   </ul>
	                   <p><%= link_to ("#{image_tag 'button.svg'}").html_safe, @hotel.external['table']['link'] + "?aid=1632186&no_rooms=1&group_adults=2&room1=A%2CA", class: 'cta-button' %></p>
	               ]]>
           </turbo:content>
        </item>
    </channel>
</rss>