config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages
  resources :hotels
  resources :sights
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'map' => 'pages#map', as: 'map'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="footer-links">
      <li>
	    <%= link_to 'Отели', hotels_path, class: 'nav-link' %>
	  </li>
	  <li>
	    <%= link_to 'Что посмотреть?', sights_path, class: 'nav-link' %>
	  </li>
	  <li>
	  	<%= link_to 'Полезное', pages_path, class: 'nav-link' %>
	  </li>
	  <li>
	    <%= link_to 'Карта', map_path, class: 'nav-link' %>
	  </li>
    </ul>
    <p><%= link_to '<strong>Kraspol.online</strong>'.html_safe, root_path %> — Отели и достопримечательности Красной Поляны</p>
    <p>© 2018 Копирование текстов без письменного разрешения владельца сайта запрещено</p>
    <ul class="list-inline payment-icons">
    	<li class="list-inline-item"><i class="fab fa-vk"></i></li>
    	<li class="list-inline-item"><i class="fab fa-facebook"></i></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<section class="header">
  <%= image_tag 'header.jpg', class: 'img-floating' %>
  <div class="title-block">
    <h1>Отели и достопримечательности <br/> Красной Поляны</h1>
    <%= link_to "Найти отели", hotels_path, class: "btn btn-lg btn-primary", "data-role" => "button" %>
    <% link_to ('Выбрать отель '+ icon('fas', 'angle-right')).html_safe, hotels_path, class: 'btn btn-lg btn-warning' %>
  </div>
</section>

app/views/layouts/_info.html.erb
<section class="info">
	<div class="container">
		<div class="title">
			<h2>Отдых в Красной Поляне, отели и достопримечательности</h2>
			<p>На сайте kraspol.online мы рады помочь вам выбрать и забронировать онлайн <%= link_to 'отель', hotels_path %> в Красной Поляне. Услуги по бронированию совершенно бесплатно, ведь мы работаем без комиссии! Вы оплачиваете лишь стоимость проживания по прибытию в отель или онлайн.</p> 
			<p>Красная Поляна — знаменитый горнолыжный курорт, расположенный на высоте около 600 метров над уровнем моря в 70 километрах от города Сочи, Красную Поляну окружают величественные горы Главного Кавказского хребта. Для вас круглый год работают канатные дороги и подъемники, которые доставят вас в любую точку курорта.</p>
			<p>Любителям горнолыжного отдыха мы рекомендуем выбрать отель в Розе Хутор — круглогодичном горнолыжном курорте, расположенном на живописном берегу реки Мзымта и горных склонах к югу от неё. Роза Хутор является самым большим горнолыжным курортом на территории Российской Федерации и располагает 28 канатными дорогами.</p>
			<p>Если горнолыжный отдых не является вашей основной целью, вы можете остановиться непосредственно в отелях поселка Красная Поляна — как правило, цены на проживание в отелях здесь ниже, чем в отелях расположенных у склонов. На нашей <%= link_to 'карте отелей Красной Поляны', map_path %> вы сможете найти отель в соответствии со своими пожеланиями к местоположению.</p>
			<p>В окрестностях Красной Поляны расположено множество природных <%= link_to 'достопримечательностей', sights_path %>: живописные каньоны, водопады, горные хребты, реки — здесь каждый сможет найти для себя место и досуг по вкусу. Отдых в Красной Поляне возможен круглый год — одни достопримечательности проявляют себя с самой живописной стороны зимой и весной, другие же благоприятны к посещению летом или осенью. Чистый воздух Красной Поляны окажет благоприятное влияние на ваше физическое самочувствие, а незабываемые пейзажи подарят вам эстетическое наслаждение и помогут привести в порядок мысли.</p>
			</p>
		</div>
	</div>
</section>

app/views/layouts/_links.html.erb
<ul class="navbar-nav">
  <li class="nav-item">
    <%= link_to 'Отели', hotels_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Что посмотреть?', sights_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Полезное', pages_path, class: 'nav-link' %>
  </li>
</ul>

app/views/layouts/_links_right.html.erb
<ul class="navbar-nav">
  <li class="nav-item">
    <%= link_to 'Карта', map_path, class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Ski Pass</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Экскурсии</a>
  </li>
  <li class="nav-item">
  	<% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "nav-link" %>
    <% end %>
  </li>
</ul>

app/views/layouts/_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter50904704 = new Ya.Metrika2({
                    id:50904704,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/tag.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks2");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/50904704" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<!-- Top100 (Kraken) Counter -->
<script>
    (function (w, d, c) {
    (w[c] = w[c] || []).push(function() {
        var options = {
            project: 6424556,
        };
        try {
            w.top100Counter = new top100(options);
        } catch(e) { }
    });
    var n = d.getElementsByTagName("script")[0],
    s = d.createElement("script"),
    f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src =
    (d.location.protocol == "https:" ? "https:" : "http:") +
    "//st.top100.ru/top100/top100.js";

    if (w.opera == "[object Opera]") {
    d.addEventListener("DOMContentLoaded", f, false);
} else { f(); }
})(window, document, "_top100q");
</script>
<noscript>
  <img src="//counter.rambler.ru/top100.cnt?pid=6424556" alt="Топ-100" />
</noscript>
<!-- END Top100 (Kraken) Counter -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

<!--  Show this only on mobile to medium screens  -->
  <%= link_to 'Красная Поляна', root_path, class: "navbar-brand d-lg-none" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<!--  Use flexbox utility classes to change how the child elements are justified  -->
  <div class="collapse navbar-collapse justify-content-between" id="navbarToggle">
    <%= render 'layouts/links' %>
<!--   Show this only lg screens and up   -->
    <%= link_to 'Красная Поляна', root_path, class: "navbar-brand d-none d-lg-block" %>
    <%= render 'layouts/links_right' %>
  </div>
</nav>

app/views/layouts/_share.html.erb
<div class="addthis_inline_share_toolbox"></div>

app/views/layouts/_top_hotels.html.erb
<section class="top-hotels">
	<div class="container">
		<div class="title">
			<h2>Топ отелей</h2>
			<p>Лучшие отели Красной Поляны для вас — выбирайте и бронируйте онлайн!</p>
		</div>
		<div class="row top-hotels-row">
			<% Hotel.all.where(top: true).limit(4).each do |hotel| %>
			<div class="col-md-6 col-xs-12 item text-center">
				<%= link_to hotel do %>
					<%= image_tag hotel.picture.url(:large), class: 'floating' %>
				<% end %>
				<div class="card">
					<div class="card-block text-center">
						<h3 class="card-title"><%= hotel.name %></h3>
						<ul class="list-inline star-rating">
			              <% hotel.stars.times do %>
			              <li class="list-inline-item star"><%= icon('fas', 'star') %></li>
			              <% end %>
			            </ul>
						<p><%= truncate(hotel.external['table']['description'], length: 90) %></p>
						<%= link_to 'Номера и цены ⟶', hotel, class: "btn btn-primary" %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</section>

app/views/layouts/_top_sights.html.erb
<section class="top-sights">
	<div class="container">
		<div class="title">
			<h2>Топ достопримечательностей</h2>
			<p>Топ достопримечательностей Красной Поляны — фото, карты, описания, как добраться и многое другое.</p>
		</div>
		<div class="row top-sights-row">
			<% Sight.all.where(top: true).limit(3).each do |sight| %>
			<div class="col-md-4 col-xs-12 item text-center">
				<%= link_to sight do %>
					<%= image_tag sight.picture.url(:main), class: 'floating' %>
				<% end %>
				<div class="top-sights-content">
					<h3><%= sight.name %></h3>
					<p><%= sight.excerpt %></p>
				</div>
				<div class="top-sights-cta">
					<div><%= link_to "Как добраться? ⟶", sight, class: "btn btn-secondary", "data-role" => "button" %></div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= display_meta_tags site: 'Отдых в Красной Поляне' %>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag	   'application' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="https://vk.com/js/api/openapi.js?159"></script>
    <script type="text/javascript">
      VK.init({apiId: 6726247, onlyWidgets: true});
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwvQaGGdHcLifD7uQ1aNmA0rPRGR5gY8I" type="text/javascript"></script>
    <meta name="google-site-verification" content="ZweS-ZS-qP7YqOLEF1b1PUFliukchx5elZIZ-lY5abA" />
    <meta name="yandex-verification" content="09cda69174d73851" />
</head>
  <body>
  	<%= render 'layouts/navbar' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4e215d296d3a8d25"></script>
    <%= render 'layouts/metrika' %>
  </body>
</html>